export let IRFconfig = {
  Laser:false,
  Hitbox:false,
  RageCreep: true,
  Uriel: true,
  Gabriel: true,
  Monstro: true,
  Adversary: true,
  DarkOne: true,
  SoulSucker: true,
  Vis: true,
  RedGhost: true,
  Goat: true,
  BrimstoneHead: true,
  Krampus: true,
  BlightedOvum: true,
  Forsaken: true,
  BloodEye: true,
  ReapCreep: true,
  Bloat: true,
  Sister: true,
  Visage: true,
  BrimBomb: true,
  Mother: true,
  Satan: true,
  TheLamb: true,
  Dogma: true,
  Gluttony: true,
  UltraGreed: true,
  Haunt: true,
  Mom: true,
  MegaSatan: true,
  TheBeast: true,
  Delirium: false,
  Pride: true,
}